services:
  category-service:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: category_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - category-service-data:/var/lib/postgresql/data
    ports:
      - "5466:5432"
    networks:
      - todo-list-network

  category-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8070:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://category-service:5432/category_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - category-service
    networks:
      - todo-list-network

volumes:
  category-service-data:
networks:
  todo-list-network:
    external: true